# Generated by Django 2.2.12 on 2020-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='name of author', max_length=20)),
                ('address', models.TextField()),
                ('phone_no', models.IntegerField()),
                ('linkedIn', models.URLField()),
                ('profile', models.TextField()),
                ('skills', models.TextField()),
                ('projects', models.TextField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('extra_curricular', models.TextField()),
            ],
        ),
    ]
