# Generated by Django 2.2.12 on 2020-08-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='email_address',
            field=models.EmailField(default='email_address', max_length=254),
        ),
        migrations.AlterField(
            model_name='cv',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='phone_no',
            field=models.PositiveIntegerField(),
        ),
    ]
